package simplenpcs;

import java.util.ArrayList;
public class OtherLists {
    
    ArrayList<String> physicalTraitList = new ArrayList<>();
    ArrayList<String> personalityTraitList = new ArrayList<>();
    ArrayList<String> occupationList = new ArrayList<>();
    ArrayList<String> motivationList = new ArrayList<>();
    ArrayList<String> secretList = new ArrayList<>();
    
    public void createOtherLists() {
        
        // physical traits
        physicalTraitList.add("Scarred");
        physicalTraitList.add("Tattoos");
        physicalTraitList.add("Missing fingers");
        physicalTraitList.add("One-eyed");
        physicalTraitList.add("Limping");
        physicalTraitList.add("Bald");
        physicalTraitList.add("Rank stench");
        physicalTraitList.add("Missing teeth");
        physicalTraitList.add("Pockmarks");
        physicalTraitList.add("Big birthmark");
        physicalTraitList.add("Freckless");
        physicalTraitList.add("Discolored skin");
        physicalTraitList.add("Squints");
        physicalTraitList.add("Lazy eye");
        physicalTraitList.add("Nose ring / piercing(s)");
        physicalTraitList.add("Tongue piercing");
        physicalTraitList.add("Nipple piercing(s)");
        physicalTraitList.add("Stooped");
        physicalTraitList.add("Thin");
        physicalTraitList.add("Lean");
        physicalTraitList.add("Chubby");
        physicalTraitList.add("Obese");
        physicalTraitList.add("Well-built");
        physicalTraitList.add("Unusual hair color");
        physicalTraitList.add("Heterochromia");
        physicalTraitList.add("Pleasant body odor");
        physicalTraitList.add("Pretty face");
        physicalTraitList.add("Exact movements");
        physicalTraitList.add("Short");
        physicalTraitList.add("Tall");
        physicalTraitList.add("Earring(s)");
        physicalTraitList.add("No chin");
        physicalTraitList.add("Strong jaw");
        physicalTraitList.add("Big nose");
        physicalTraitList.add("Painted lips");
        physicalTraitList.add("Toothless");
        physicalTraitList.add("Blind");
        physicalTraitList.add("No tongue");
        physicalTraitList.add("Deaf");
        physicalTraitList.add("Handsome / beautiful");
        physicalTraitList.add("Sweaty");
        physicalTraitList.add("Lip piercing(s)");
        physicalTraitList.add("Hairy (or other)");
        physicalTraitList.add("Thin eyes");
        physicalTraitList.add("Large eyes");
        physicalTraitList.add("Missing arm");
        physicalTraitList.add("Missing leg");
        physicalTraitList.add("Missing hand");
        physicalTraitList.add("Missing foot");
        physicalTraitList.add("Peg leg");
        physicalTraitList.add("Giggles inappropiately");
        physicalTraitList.add("Wheezing cough");
        physicalTraitList.add("Snores");
        physicalTraitList.add("Constantly flexes muscles");
        physicalTraitList.add("Clumsy");
        physicalTraitList.add("Missing ear");
        physicalTraitList.add("Lithe");
        physicalTraitList.add("Moves in a crouch");
        physicalTraitList.add("Dextrous");
        physicalTraitList.add("Fat");
        physicalTraitList.add("Whistles");
        physicalTraitList.add("Cross-eyed");
        physicalTraitList.add("Filthy");
        physicalTraitList.add("Surprisingly clean");
        physicalTraitList.add("Venerial disease");
        physicalTraitList.add("Unusual eye color");
        //physicalTraitList.add("");
        
        // personality traits
        personalityTraitList.add("Arachnophobia");
        personalityTraitList.add("Agoraphobia");
        personalityTraitList.add("Fear of the Dark");
        personalityTraitList.add("Fear of cats");
        personalityTraitList.add("Fear of dogs");
        personalityTraitList.add("Fear of birds");
        personalityTraitList.add("Fear of bathing");
        personalityTraitList.add("Fear of running water");
        personalityTraitList.add("Distrustful");
        personalityTraitList.add("Cruel");
        personalityTraitList.add("Happy-go-lucky");
        personalityTraitList.add("Stoic");
        personalityTraitList.add("Greedy");
        personalityTraitList.add("Know-it-all");
        personalityTraitList.add("Depressed");
        personalityTraitList.add("Morose");
        personalityTraitList.add("Moody");
        personalityTraitList.add("Altruist");
        personalityTraitList.add("Calm");
        personalityTraitList.add("Nervous");
        personalityTraitList.add("Artistic");
        personalityTraitList.add("Helpful");
        personalityTraitList.add("Will to power");
        personalityTraitList.add("Patriotic");
        personalityTraitList.add("Xenophobic");
        personalityTraitList.add("Easily distracted");
        personalityTraitList.add("Ditzy");
        personalityTraitList.add("Distrusts magic");
        personalityTraitList.add("Envious");
        personalityTraitList.add("Sarcastic");
        personalityTraitList.add("Sardonic");
        personalityTraitList.add("Caustic tongue");
        personalityTraitList.add("Evil");
        personalityTraitList.add("Sociopath");
        personalityTraitList.add("Narcicist");
        personalityTraitList.add("Likes pretty things");
        personalityTraitList.add("A little slow");
        personalityTraitList.add("Quick to anger");
        personalityTraitList.add("Coward");
        personalityTraitList.add("Brave");
        personalityTraitList.add("Adventurous");
        personalityTraitList.add("Clever");
        personalityTraitList.add("Extrovert");
        personalityTraitList.add("Introvert");
        personalityTraitList.add("Misanthrope");
        personalityTraitList.add("Pious");
        personalityTraitList.add("Drunk");
        personalityTraitList.add("Addicted to sex");
        personalityTraitList.add("Addicted to drugs");
        personalityTraitList.add("Caffeine addict");
        personalityTraitList.add("Excessively polite");
        personalityTraitList.add("Amused");
        personalityTraitList.add("Tight lipped");
        personalityTraitList.add("Helpful");
        personalityTraitList.add("Vicious");
        personalityTraitList.add("Bloody-minded");
        //personalityTraitList.add("");
        
        // occupation / background
        occupationList.add("Soldier");
        occupationList.add("Sage");
        occupationList.add("Wanderer");
        occupationList.add("Herbalist");
        occupationList.add("Merchant");
        occupationList.add("Thief");
        occupationList.add("Assassin");
        occupationList.add("Noble");
        occupationList.add("Courier");
        occupationList.add("Razor-Cage fighter");
        occupationList.add("Herald");
        occupationList.add("Peasant");
        occupationList.add("Blacksmith");
        occupationList.add("Hedge mage");
        occupationList.add("Warrior");
        occupationList.add("Clerk");
        occupationList.add("Guard");
        occupationList.add("Beer crafter");
        occupationList.add("Beekeeper");
        occupationList.add("Coachman");
        occupationList.add("Servant");
        occupationList.add("Courtesan");
        occupationList.add("Witch");
        occupationList.add("Poet");
        occupationList.add("Mime");
        occupationList.add("Dancer");
        occupationList.add("Painter");
        occupationList.add("Priest");
        occupationList.add("Monk");
        occupationList.add("Musician");
        occupationList.add("Bard");
        occupationList.add("Boatman");
        occupationList.add("Navigator");
        occupationList.add("Gamekeeper");
        occupationList.add("Executioner");
        occupationList.add("Pastry chef");
        occupationList.add("Cook");
        occupationList.add("Waiter");
        occupationList.add("Miner");
        occupationList.add("Fence");
        occupationList.add("Loanshark");
        occupationList.add("Beast wrangler");
        occupationList.add("Shepherd");
        occupationList.add("Nomad");
        occupationList.add("Spy");
        occupationList.add("Secret police");
        occupationList.add("Baker");
        occupationList.add("Drug dealer");
        occupationList.add("Scout");
        occupationList.add("Warden");
        occupationList.add("Exiled noble");
        occupationList.add("Disgraced officer");
        occupationList.add("Failed innkeeper");
        occupationList.add("Layabout");
        occupationList.add("Hunter");
        occupationList.add("Trapper");
        occupationList.add("Lumberjack");
        occupationList.add("Detective");
        occupationList.add("Scavenger");
        occupationList.add("Drunk");
        occupationList.add("Jester");
        occupationList.add("Flutist");
        occupationList.add("Actor");
        occupationList.add("Tanner");
        occupationList.add("Leatherworker");
        occupationList.add("Butcher");
        occupationList.add("Gardener");
        occupationList.add("Retired military person");
        occupationList.add("Ex-courtesan");
        occupationList.add("Falconer");
        occupationList.add("Gravedigger");
        occupationList.add("Hermit");
        occupationList.add("Architect");
        occupationList.add("Bandit");
        occupationList.add("Alchemist");
        occupationList.add("Jeweler");
        occupationList.add("Archer");
        occupationList.add("Tinker");
        occupationList.add("Rat catcher");
        occupationList.add("Locksmith");
        occupationList.add("Pimp");
        occupationList.add("Harlot");
        occupationList.add("Poacher");
        occupationList.add("Playwright");
        occupationList.add("Sheriff");
        occupationList.add("Furrier");
        occupationList.add("Slaver");
        //occupationList.add("");
        
        // motivations
        motivationList.add("Acquire political power");
        motivationList.add("Spiritual search");
        motivationList.add("Wealth");
        motivationList.add("Carnal pleasures");
        motivationList.add("Revolution");
        motivationList.add("Keep the races apart");
        motivationList.add("Magical power");
        motivationList.add("Lift a curse");
        motivationList.add("Keep the family fed");
        motivationList.add("Find a better job");
        motivationList.add("Glory");
        motivationList.add("Acquire criminal power");
        motivationList.add("Maintain status quo");
        motivationList.add("Get educated");
        motivationList.add("Excellence in their field");
        motivationList.add("Impart knowledge");
        motivationList.add("Vengeance");
        motivationList.add("Find a cure");
        motivationList.add("Maintain territory");
        motivationList.add("Get royally drunk");
        motivationList.add("Retirement");
        motivationList.add("Liberation");
        motivationList.add("Break someone out of prison");
        motivationList.add("Win someone's heart");
        motivationList.add("Persecute political opponents");
        motivationList.add("Persecute heretics");
        motivationList.add("Civilize the Wilds");
        motivationList.add("Tear down civilization");
        motivationList.add("Escape from a loveless marriage");
        motivationList.add("Acquire new experiences");
        motivationList.add("Murder an innocent");
        motivationList.add("Adventure");
        motivationList.add("Become a sea captain");
        motivationList.add("Join an army");
        motivationList.add("Join a navy");
        motivationList.add("Make a great magical discovery");
        motivationList.add("Make a great scientific discovery");
        motivationList.add("Disgrace a rival");
        motivationList.add("Go on a pilgrimage");
        motivationList.add("Visit a famous grave");
        motivationList.add("Get freaky!");
        //motivationList.add("");

        secretList.add("Murdered someone in cold blood");
        secretList.add("Caused the death of a loved one");
        secretList.add("Sexual deviant");
        secretList.add("Stole from a powerful person");
        secretList.add("Deserter");
        secretList.add("Secret cultist");
        secretList.add("Demon worshipper");
        secretList.add("Drug user");
        secretList.add("Functioning drunk");
        secretList.add("Planning a coup");
        secretList.add("Traitor to their country");
        secretList.add("Traitor to their organization");
        secretList.add("Is really an undead in disguise");
        secretList.add("Stole the body they are wearing");
        secretList.add("Beats their spouse regularly");
        secretList.add("Abuses their children");
        secretList.add("Reformed cultist");
        secretList.add("Reformed devil worshipper");
        secretList.add("Recovering substance abuser");
        secretList.add("Is a monster masquerading as a person");
        secretList.add("Strangled their mother");
        secretList.add("Killed their father");
        secretList.add("Strangled their child");
        secretList.add("Accidentally summoned a demon");
        secretList.add("Accidentally raised the dead");
        secretList.add("Former notorious criminal");
        secretList.add("Belongs to a criminal organization");
        secretList.add("Ate the flesh of their enemy");
        secretList.add("Failed priest or monk");
        secretList.add("A host to an interplanar horror");
        secretList.add("Is really a nice person");
        secretList.add("Is really a very poor person");
        secretList.add("Secretly wealthy");
        secretList.add("Stole their current identity");
        secretList.add("Twin to an important person");
        secretList.add("Disgraced noble");
        secretList.add("Ousted ruler");
    }
}
